import React from 'react';

const Termscondition = () => {
    return(
        <section >
            <div className='bg-neutral-100 px-10 pb-10 sm-only:px-0'>
                <div className="flex justify-center">
                    <div>
                        <div className="sm-only:mt-11">
                            <p className="mt-6 text-center text-gray-500 sm-only:mt-1.5 mb-1.5 text-xs">Home | Terms & Use</p>
                            <h1 className="text-center text-3xl font-semibold sm-only:text-2xl">Terms & Use</h1>
                        </div>

                        <div className="bg-white py-4 my-5 w-11/12 mx-auto sm-only:my-3 pt-px ">
                            <div className="sm-only:px-2 mt-1.5 space-y-1.5  lg-only:text-justify mt-5 px-10">
                                <p>Welcome to thinkitchen.in ! We are part of "SEEBA INDUSTRIES PRIVATE LIMITED". Thinkitchen and/or its affliates provide services when you visit and use the Website. This user agreement (“Terms and Conditions” or “T&C” or “Terms” or “Agreement”) is between you (“you” or “End User” or “your” or “Buyer” or “Customer” or “Registered User”) and THINKITCHEN (“Company” or “us” or “We” or “thinkitchen.in”). These Terms of Use apply to your access and use of the Website.</p>
                                <p>These policies are published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, and are an ‘electronic record’ as contemplated under section 2(t) of the Information Technology Act, 2000 and the Rules thereunder. These Terms being an electronic record are generated by a computer system and do not require any physical or digital signatures. </p>
                                <p className='pb-5 border-b border-gray-300 sm-only:pb-2.5'>Our store is hosted on Shopify Inc. They provide us with the online e-commerce platform that allows us to sell our products and services to you. The headings used in this agreement are included for convenience only and will not limit or otherwise affect these Terms. </p>
                            </div>

                            <div className='sm-only:px-2 mt-2 space-y-1.5 lg-only:text-justify px-10'>
                                <p className='sm-only:font-bold pt-1 pb-0 lg:font-bold'>THESE TERMS AND CONDITIONS MAY CHANGE</p>
                                <p className='pb-5 border-b border-gray-300 sm-only:pb-2.5'>THINKITCHEN reserves the right to update or modify these Terms of Use at any time without prior notice. Those changes will go into effect on the Last Updated Date shown in the revised Terms of Use. By continuing to use the Website, you are agreeing to the revised Terms of Use. For this reason, we encourage you to review these Terms whenever you purchase products from us or use our Website.</p>
                            </div>

                            <div className='sm-only:px-2 mt-2 space-y-1.5  lg-only:text-justify px-10'>
                                <p className='font-bold'>PERSONAL INFORMATION</p>
                                <p className='pb-5 border-b border-gray-300 sm-only:pb-2.5'>We are committed to protect your privacy and personal information. For more information on our Privacy policies. </p>
                            </div>

                            <div className='sm-only:px-2 mt-2 space-y-1.5 lg-only:text-justify px-10'>
                                <p className='font-bold pt-1 pb-0 '>USE OF PROPRIETARY MATERIAL</p>
                                <p>Any proprietary material owned by a third party and so expressly mentioned, THINKITCHEN owns all Intellectual Property Rights to and into the Website, including, without limitation, any and all rights, title and interest in and to copyright, related rights, patents, utility models, trademarks, trade names, service marks, designs, know-how, trade secrets and inventions (whether patentable or not ), goodwill, source code, meta tags, databases, text, content, graphics, icons, and hyperlinks. You acknowledge and agree that you shall not use, reproduce or distribute any content from the Website belonging to THINKITCHEN without obtaining authorization from it. </p>
                                <p className='pb-5 border-b border-gray-300 sm-only:pb-2.5'>Our Website may also contain copyrighted material, trademarks and other proprietary information, including, but not limited to, text, software, photos, video, graphics, music , sound, and the entire contents of THINKITCHEN protected by copyright as a collective work under the applicable copyright laws. THINKITCHEN owns a copyright in the selection, coordination, arrangement and enhancement of such content, as well as in the content original to it. Users may not modify, publish, transmit, participate in the transfer or sale, create derivative works, or in any way exploit, any of the content, in whole or in part. Users may download / print / save copyrighted material for the User’s personal use only. Except as otherwise expressly stated under copyright law, no copying, redistribution, retransmission, publication or commercial exploitation of downloaded material without the express permission of THINKITCHEN and the copyright owner is permitted.</p>
                            </div>

                            <div className='sm-only:px-2 mt-2 space-y-1.5  lg-only:text-justify px-10'>
                                <p className='font-bold pt-1 pb-0'>ACCURACY, COMPLETENESS AND TIMELINESS OF INFORMATION</p>
                                <p className='pb-5 border-b border-gray-300 sm-only:pb-2.5'>At THINKITCHEN, we attempt make the information provided to you as accurate as possible. However, we do not warrant that the information made available on this website is accurate, complete or current. The material on this Website is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary, more accurate, more complete or more timely sources of information. If a product offered by us is not as described, your sole remedy is to contact THINKITCHEN within 48 hours of receipt. THINKITCHEN is not liable to issue any refunds or allow exchanges and/or returns as a matter of policy.</p>
                            </div>

                            <div className='sm-only:px-2 mt-2 space-y-1.5 lg-only:text-justify px-10'>
                                <p className='font-bold pt-1 pb-0'>PRODUCT PRICING AND BILLING INFORMATION</p>
                                <p>The prices displayed on our Website are the Maximum Retail Price (MRP) and are inclusive of all local taxes as applicable in India. The prices may differ from prices that are available in stores or in catalogs, and our pricing may differ from store to store.</p>
                                <p className='pb-5 border-b border-gray-300 sm-only:pb-2.5'>We may also charge shipping and processing feeds that are intended to compensate us for the cost of processing an order, handling and packing the products purchased and delivering them to you. This include a delivery / shipment charge. For sale products (identified by pricing in red), "Suggested Price" or "Sugg. Price" refers to the most recent selling price. "Sale" refers to the reduced price we are offering to our customers.</p>
                            </div>

                            <div className='sm-only:px-2 mt-2 space-y-1.5 lg-only:text-justify px-10'>
                                <p className='font-bold pt-1 pb-0'>ORDER CANCELLATION</p>
                                <p className='pb-5 border-b border-gray-300 sm-only:pb-2.5'>Under unavoidable circumstances, THINKITCHEN may have to cancel certain orders that may not be processes or dispatched. We reserve the right to refuse any order you place with cancel or us any order for any reason. We may, in our sole discretion, limit or cancel quantities purchased per person, per household or per order. These restrictions may include orders placed by or under the same customer account, the same credit card, and/or orders that use the same billing and/or shipping address. In the event that we make a change to or cancel an order, we may attempt to notify you by contacting the e‑mail and/or billing address/phone number provided at the time the order was made. We reserve the right to limit or prohibit orders that, in our sole judgment, appear to be placed by dealers, resellers or distributors. For further information on our Returns policy.</p>
                            </div>

                            <div className='sm-only:px-2 mt-2  space-y-1.5 lg-only:text-justify px-10 '>
                                <p className='font-bold pt-1 pb-0 '>DELIVERY</p>
                                <p>We aim to deliver orders placed by you on time to the shipping address. However, please note that it might not be possible for us to deliver to some locations as requested in your order. If this is the case, we will inform you using the contact details that you provide to us when you place your order and arrange for cancellation of the order or delivery to an alternative shipping address. We endeavor to deliver within the stipulated time frame of any order but we cannot guarantee any firm delivery dates and we would update you accordingly if we could reasonably foresee that we are unable to meet our estimated delivery date, but, to the extent permitted by law, we shall not be liable to you for any losses, liabilities, costs, damages, charges or expenses arising out of late delivery.</p>
                                <p className='pb-5 border-b border-gray-300 sm-only:pb-2.5'> Upon delivery of the product, you may be required to sign for delivery. You agree to inspect the product for any obvious faults, defects or damage before you sign for delivery. You need to keep receipt of the delivered product as reference in case of future communication with us. All risk in the product shall pass to you upon delivery, except that, where delivery is delayed due to a breach of your obligations under a contract, risk shall pass at the date when delivery would have occurred but for your breach. From the time when risk passes to you, we will not be liable for loss or destruction of the product. You must be careful when opening the product so as not to damage it, particularly when using any sharp instruments.</p>
                            </div>

                            <div className='sm-only:px-2 mt-2  space-y-1.5 lg-only:text-justify px-10 '>
                                <p className='font-bold pt-1 pb-0'>RETURNS & REFUNDS</p>
                                <p className='pb-5 border-b border-gray-300 sm-only:pb-2.5'> THINKITCHEN shall make all endeavors to deliver defect free products to the purchasers. However, we do not take title to any returned items purchased by the user unless the item is received by us. Any item purchased on our website does not qualify for any return unless the product delivered is damaged or has manufacturing defects. The defective and/or damaged goods so received shall be communicated to THINKITCHEN within 48 hours of its receipt. Any communication received after 48 hours of delivery shall not qualify for return unless expressly covered by the product warranty even in case the said product has been wrongly delivered. THINKITCHEN holds the sole discretion to determine whether a refund can be issued. For further information please read our Returns policy.</p>
                            </div>

                            <div className='sm-only:px-2 mt-2  space-y-1.5  lg-only:text-justify px-10 '>
                                <p className='font-bold pt-1 pb-0'>SPECIAL OFFERS & GIFT VOUCHERS</p>
                                <p>Occasionally we will offer special promotions to our customers that we refer to as "special offers" or "special offer". This can include a gift with purchase, free shipping, manufacturer offers, or other promotional activity associated with a product purchase. These offers may be for a limited time only.</p>
                                <p className='pb-5 border-b border-gray-300 sm-only:pb-2.5'> Gift vouchers are also provided occasionally and can be redeemed on our Website. The offers on these vouchers may vary and may be offered for a limited time only. Please refer to the terms and conditions mentioned on the vouchers.</p>
                            </div>

                            <div className='sm-only:px-2 mt-2 space-y-1.5 lg-only:text-justify px-10 '>
                                <p className='font-bold pt-1 pb-0 '>DISCLAIMER OF WARRANTIES; LIMITATION OF LIABILITY</p>
                                <p>We do not guarantee, represent or warrant that your use of our service will be uninterrupted, timely, secure or error-free. We do not warrant that the results that may be obtained from the use of the service will be accurate or reliable. You agree that from time to time we may remove the service for indefinite periods of time or cancel the service at any time, without notice to you. You expressly agree that your use of, or inability to use, the service is at your sole risk. The service and all products and services delivered to you through the service are (except as expressly stated by us) provided 'as is' and 'as available' for your use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and non-infringement.</p>
                                <p className='pb-5 border-b border-gray-300 sm-only:pb-2.5'>In no case shall , our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, service providers or licensors be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from your use of any of the service or any products procured using the service, or for any other claim related in any way to your use of the service or any product, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the service or any content (or product) posted, transmitted, or otherwise made available via the service, even if advised of their possibility. Because some states or jurisdictions do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, our liability shall be limited to the maximum extent permitted by law.</p>
                            </div>

                            <div className='sm-only:px-2 mt-2 space-y-1.5 lg-only:text-justify px-10 '>
                                <p className='font-bold pt-1 pb-0 '>INDEMNIFICATION</p>
                                <p className='pb-5 border-b border-gray-300 sm-only:pb-2.5'>To the fullest extent permitted by applicable law, uou agree to indemnify, defend and hold harmless THINKITCHEN and our parent, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensors, service providers, subcontractors, suppliers, interns and employees, harmless from any claim or demand, including reasonable attorneys’ fees, made by any third-party due to or arising out of your breach of these Terms or the documents they incorporate by reference, or your violation of any law or the rights of a third-party.</p>
                            </div>

                            <div className='sm-only:px-2 mt-2 space-y-1.5 lg-only:text-justify px-10 '>
                                <p className='font-bold pt-1 pb-0 '>SEVERABILITY</p>
                                <p className='pb-5 border-b border-gray-300 sm-only:pb-2.5'>In the event that any provision of these Terms is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms, such determination shall not affect the validity and enforceability of any other remaining provisions.</p>
                            </div>

                            <div className='sm-only:px-2 mt-2  space-y-1.5 lg-only:text-justify px-10 '>
                                <p className='font-bold pt-1 pb-0 '>TERMINATION</p>
                                <p>The obligations and liabilities of the parties incurred prior to the termination date shall survive the termination of this agreement for all purposes. These Terms are effective unless and until terminated by either you or us. You may terminate these Terms of Use at any time by notifying us that you no longer wish to use our Services, or when you cease using our site. </p>
                                <p className='pb-5 border-b border-gray-300 sm-only:pb-2.5'>If in our sole judgment you fail, or we suspect that you have failed, to comply with any term or provision of these Terms of Service, we also may terminate this agreement at any time without notice and you will remain liable for all amounts due up to and including the date of termination; and/or accordingly may deny you access to our Services (or any part thereof).</p>
                            </div>

                            <div className='sm-only:px-2 mt-2  space-y-1.5  lg-only:text-justify px-10 '>
                                <p className='font-bold pt-1 pb-0 '>ENTIRE AGREEMENT    </p>
                                <p className='pb-5 border-b border-gray-300 sm-only:pb-2.5'>The failure of us to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision. These Terms any policies or operating rules posted by us on this site or in respect to The Service constitutes the entire agreement and understanding between you and us and govern your use of the Service, superseding any prior or contemporaneous agreements, communications and proposals, whether oral or written, between you and us (including, but not limited to, any prior versions of the Terms of Use). Any ambiguities in the interpretation of these Terms of Use shall not be construed against the drafting party.</p>
                            </div>

                            <div className='sm-only:px-2 mt-2  space-y-1.5  lg-only:text-justify px-10 ' >
                                <p className='font-bold pt-1 pb-0 '>GOVERNING LAW</p>
                                <p className='pb-5 border-b border-gray-300 sm-only:pb-2.5'>These Terms of Service and any separate agreements whereby we provide you Services shall be governed by and construed in accordance with the laws of India.</p>
                            </div>

                            <div className='sm-only:px-2 mt-2 space-y-1.5 lg-only:text-justify px-10 '>
                                <p className='font-bold pt-1 pb-0'>CONTACT INFORMATION</p>
                                <p className='pb-2 sm-only:pb-2.5'>Any suestions about the Terms of Use should be addressed to ‘Customer Care’ by way of email to customercare@seebagroup.com.</p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>
    );

}

export default Termscondition;